### ISSUE TITLE
Ghidra v10.0 has been released

### ISSUE THREAD

**Issue by Barracuda6** [flathub/org.ghidra_sre.Ghidra#6]
Ghidra v10.0 has been released, could we please have an update to the flatpak version as well?

**Comment by hadess** [comment]
You can test the new package in https://github.com/flathub/org.ghidra_sre.Ghidra/pull/8

I haven't had time to run basic tests to ensure that it works, so it'll have to wait a couple of days until I have the time.

**Comment by hadess** [comment]
FWIW, Ghidra is still broken on OSTree: https://github.com/NationalSecurityAgency/ghidra/issues/3726 after being broken on OSTree: https://github.com/NationalSecurityAgency/ghidra/issues/3377 which is why it wasn't updated.

**Comment by hadess** [comment]
Upgraded in https://github.com/flathub/org.ghidra_sre.Ghidra/pull/18
